variable "vm_name" {}
variable "location" {}
variable "rg_name" {}
variable "size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "storage_account_type" {}
variable "nic_name" {}
